cache:
    type: "redis"
    host: "$DINO_REDIS_HOST"
    db: $DINO_REDIS_DB

db:
    uri: "$DINO_DB_URI"
    user: "$DINO_DB_USERNAME"
    password: "$DINO_DB_PASSWORD"

storage:
    host: "$DINO_STORAGE_HOSTS"
    key_space: "$DINO_STORAGE_KEY_SPACE"
    user: "$DINO_STORAGE_USERNAME"
    password: "$DINO_STORAGE_PASSWORD"

logging:
    type: "$DINO_LOG_TYPE"
    dsn: "$DINO_LOG_DSN"
    trace_sample_rate: "$DINO_TRACE_SAMPLE_RATE"

kafka:
    host: "$DINO_KAFKA_HOST"
    topic: "$DINO_KAFKA_TOPIC"
    dropped_log: "$DINO_KAFKA_DROPPED_LOG"

stats:
    type: 'statsd'
    host: '$DINO_STATSD_HOST'
    port: 8125
    prefix: '$DINO_STATSD_PREFIX'
    include_hostname: 'true'

mqtt:
    host: "$DINO_MQTT_HOST"
    port: "$DINO_MQTT_PORT"
    ttl: "$DINO_MQTT_TTL"
    user: "$DINO_MQTT_USER"
    password: "$DINO_MQTT_PASS"

mqtt_auth:
    type: "$DINO_MQTT_AUTH_TYPE"
    host: "$DINO_MQTT_AUTH_HOST"
    db: "$DINO_MQTT_AUTH_DB"
    user: "$DINO_MQTT_AUTH_USER"
    password: "$DINO_MQTT_AUTH_PASS"

publisher:
    host: "$DINO_PUB_HOST"
    db: "$DINO_PUB_DB"
    stream: "$DINO_PUB_STREAM"
    group: "$DINO_PUB_GROUP"
    block: "$DINO_PUB_BLOCK"
