site_name: Dino
site_url: https://thenetcircle.github.io/dino-service/
nav:
    - Home: index.md
    - Usage: md/usage.md
    - Events: md/events.md
    - Public Groups: md/public.md
    - REST API: md/rest_api.md
theme: readthedocs
