DINO_STORAGE_HOSTS: "storage-host-1,storage-host-2"
DINO_STORAGE_KEY_SPACE: "dinoms"
DINO_DB_URI: "mysql://user:pass@mysql-host-1/dinoms"
DINO_STORAGE_PASSWORD: "pass"
DINO_STORAGE_USERNAME: "user"
DINO_COORDINATOR_HOST: "redis-host-1"
DINO_COORDINATOR_DB: 0
DINO_KAFKA_HOSTS: "kafka-host-1:9094"
DINO_KAFKA_TOPIC: "event-dinoms-broadcasts"
DINO_REDIS_HOST: "redis-host-1:6379"
DINO_REDIS_DB: 5
DINO_MQTT_HOST: "mqtt-host-1"
DINO_MQTT_PORT: 1883
DINO_MQTT_TTL: 10